// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stjojtpvhiojcodfqyqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0am9qdHB2aGlvamNvZGZxeXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjI5OTIsImV4cCI6MjA2NTUzODk5Mn0.XDjUS1SRQ-RM5ETxea9MOkSvZP_yH1Lhxq6X18cZiHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);